spring:
  application:
    name: papergenerator

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: school_ai_db

  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: llama3.1:8b
      embedding:
        options:
          model: nomic-embed-text

    vectorstore:
      pinecone:
        apiKey: ${PINECONE_API_KEY}
        index-name: "school-notes"
        project-id: "r3jj6iu"
        environment: "aped-4627-b74a"
        namespace: "default"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
